### ISSUE TITLE
도쿄크레이타구락부 두들 

### ISSUE THREAD

**Issue by flyin98** [flyin98/TokyoCreatorClub#3]
### 페이스북 페이지의 커버 사진을 구글 두들처럼 사용해 만들어 보아요
1. 월별로 나누어 한사람씩 만들어갑니다.
2. 디자인한 이미지를 이슈에 등록합니다.
3. 디자인 리뷰
4. 페이스북에 등록
5. 회식
6. 회식 2차
7. 회식 3차

### 구글 두들 의 예

요딴거임
![newyear2014doodle](https://cloud.githubusercontent.com/assets/8437720/13519150/35151e9c-e218-11e5-9fae-a56019024ed7.gif)

https://en.wikipedia.org/wiki/Google_Doodle

## 정윤탁 님 (nazonoz)

잘 부탁 드립니다!

**Comment by flyin98** [comment]
@nazonoz
잘부탁해요~~ㅎㅎ

**Comment by img75** [comment]
@flyin98 아 이미 만드셨구나! 제껀 삭제합니다.
